using System;
using System.Collections.Generic;

namespace PrismStrap.Services
{
    public static class LocalizationService
    {
        public static string CurrentLanguage { get; private set; } = "ja";

        public static readonly (string Code, string Label)[] SupportedLanguages = new[]
        {
            ("ja", "🇯🇵 日本語"),
            ("en", "🇺🇸 English"),
            ("ko", "🇰🇷 한국어"),
            ("id", "🇮🇩 Bahasa Indonesia"),
            ("zh", "🇨🇳 简体中文"),
            ("pt", "🇧🇷 Português")
        };

        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
        {
            ["ja"] = new()
            {
                ["NavHome"] = "概要",
                ["NavPerf"] = "パフォーマンス",
                ["NavGfx"] = "グラフィック",
                ["NavSounds"] = "サウンド",
                ["NavFlags"] = "FastFlags",
                ["NavMods"] = "外観・MOD",
                ["NavSys"] = "システム統合",

                ["ModsTitle"] = "外観 & MOD設定",
                ["ModsDesc"] = "ゲーム内フォント、マウスポインター、アプリアイコンを自由にカスタマイズします",
                ["FontCardTitle"] = "ゲーム内カスタムフォント",
                ["FontCardDesc"] = "RobloxのUIやチャットのフォントをお好みの書体に変更します",
                ["FontDefault"] = "公式デフォルト (Builder Sans)",
                ["FontComicSans"] = "Comic Sans MS (手書き風・高視認性)",
                ["FontSegoeUI"] = "Segoe UI (Windows 11 Fluent)",
                ["FontArial"] = "Arial (シンプル・クリーン)",
                ["FontCustom"] = "カスタムフォント (.ttf / .otf)",
                ["SelectFontFile"] = "フォントファイルを選択...",
                ["FontPreviewLabel"] = "プレビュー: Roblox を美しく、軽快に。The quick brown fox jumps over the lazy dog 1234567890",

                ["CursorCardTitle"] = "マウスポインター (カーソル)",
                ["CursorCardDesc"] = "Robloxゲーム内のマウスポインターをお好みのデザインに変更します",
                ["CursorDefault"] = "公式デフォルト (2020+)",
                ["CursorClassic2013"] = "クラシック 2013-2020 (太枠白矢印)",
                ["CursorClassic2006"] = "クラシック 2006-2013 (レトロピクセル)",
                ["CursorCleanModern"] = "クリーン Modern (Windows 11風)",
                ["CursorCustom"] = "カスタム画像 (.png)",
                ["SelectCursorFile"] = "画像ファイルを選択...",

                ["IconCardTitle"] = "Roblox アプリアイコン",
                ["IconCardDesc"] = "デスクトップやスタートメニュー、タスクバーのRobloxアイコンを着せ替えます",
                ["IconModern2022"] = "Modern 2022 (最新シルバー)",
                ["IconTilted2017"] = "Classic 2017 (名作チルトレッド)",
                ["IconRedSquare2015"] = "Classic 2015 (レッドブロック)",
                ["IconClassic2008"] = "Classic 2008 (伝説の赤Rロゴ)",
                ["IconPrismNeon"] = "PrismStrap ネオンプリズム",
                ["BtnApplyIcon"] = "アイコンを今すぐ適用",
                ["IconAppliedSuccess"] = "アプリアイコンを正常に適用しました！",

                ["BtnLaunchRoblox"] = "Robloxを起動",
                ["BtnCheckUpdates"] = "更新を確認",
                ["StatusReady"] = "Roblox: 準備完了",
                ["StatusChecking"] = "更新を確認中...",
                ["StatusLatest"] = "Roblox: 最新版 (準備完了)",
                ["StatusError"] = "確認エラー",
                ["StatusDownloading"] = "更新ダウンロード中...",

                ["HomeTitle"] = "PrismStrap",
                ["HomeSubtitle"] = "Robloxのための次世代ブートストラッパー & 最適化ツール",
                ["SysInfoTitle"] = "システム情報",
                ["CurrentVersion"] = "現在のバージョン",
                ["RobloxDir"] = "Robloxフォルダ",
                ["PlayerExe"] = "実行ファイル",
                ["QuickStatsTitle"] = "現在の最適化ステータス",
                ["StatFps"] = "FPS上限",
                ["StatGfx"] = "グラフィックAPI",
                ["StatSound"] = "死亡サウンド",
                ["StatProtocol"] = "ブラウザ連携",

                ["PerfTitle"] = "パフォーマンス設定",
                ["PerfDesc"] = "Robloxのフレームレート制限やCPU/GPU負荷を最適化します",
                ["FpsCardTitle"] = "フレームレート上限解除 (FPS Unlocker)",
                ["FpsCardDesc"] = "Robloxの標準60FPS制限を解除します。0に設定すると上限なし（無制限）になります。",
                ["TargetFpsLabel"] = "目標フレームレート (FPS)",
                ["PresetsLabel"] = "プリセット",
                ["Unlimited"] = "無制限",
                ["SaveSettings"] = "設定を保存して適用",

                ["GfxTitle"] = "グラフィック & レンダリング",
                ["GfxDesc"] = "GPUレンダリングバックエンドやグラフィックス品質を設定します",
                ["ApiCardTitle"] = "レンダリングAPI",
                ["ApiCardDesc"] = "Robloxの画面描画に使用するグラフィックエンジンを選択します",
                ["ApiAuto"] = "自動 (Direct3D 11/自動検出)",
                ["ApiVulkan"] = "Vulkan (低遅延・高フレームレート)",
                ["ApiD3d11"] = "Direct3D 11 (安定性重視)",
                ["FeaturesTitle"] = "グラフィックオプション",
                ["MaxTexture"] = "テクスチャ品質最大化",
                ["MaxTextureDesc"] = "距離に関わらず最高解像度のテクスチャを強制適用します",
                ["DisablePostFx"] = "ポストエフェクト無効化",
                ["DisablePostFxDesc"] = "ブラーや色調補正などのポストプロセスを無効化して視認性を向上します",
                ["ClassicMenu"] = "クラシックEscメニュー",
                ["ClassicMenuDesc"] = "2020年以前の旧式Escメニューデザインを復元します",

                ["SoundsTitle"] = "サウンド & 効果音",
                ["SoundsDesc"] = "Robloxの効果音をカスタマイズしてゲーム体験を向上させます",
                ["DeathSoundCardTitle"] = "死亡時サウンド (OOF音)",
                ["DeathSoundCardDesc"] = "キャラクターがリセットまたは倒れた時に再生される効果音（ouch.ogg）を変更します。",
                ["SoundClassicOof"] = "元祖 Roblox OOF サウンド (2006-2022)",
                ["SoundVineBoom"] = "Vine Boom (人気ミーム音)",
                ["SoundCustom"] = "カスタム MP3 音源",
                ["SoundDefault"] = "Roblox 標準サウンド (公式デフォルト)",
                ["BrowseFile"] = "MP3ファイルを選択...",
                ["BtnPreview"] = "▶ 試聴する",
                ["BtnApplySound"] = "サウンドを適用",
                ["CustomFileLabel"] = "選択中のファイル: ",
                ["NoFileSelected"] = "ファイルが未選択です",
                ["LblAudioEffectsTitle"] = "音響エフェクト調整",
                ["LblAudioEffectsDesc"] = "死亡時サウンドの音量と再生速度（ピッチ）をカスタマイズします",
                ["LblVolume"] = "音量 (Volume)",
                ["LblSpeed"] = "再生速度 (Speed / ピッチ連動)",
                ["BtnResetAudio"] = "初期値にリセット",
                ["LoadingStartingRoblox"] = "Roblox を起動しています...",
                ["LoadingApplyingMods"] = "FastFlags とカスタムサウンドを適用中...",
                ["LoadingCheckingUpdates"] = "Roblox の更新を確認中...",
                ["LoadingCancel"] = "キャンセル",

                ["FlagsTitle"] = "FastFlags エディター",
                ["FlagsDesc"] = "Robloxの内部実験的フラグ (ClientAppSettings.json) を直接編集します",
                ["AddFlagTitle"] = "新しいFastFlagを追加",
                ["FlagKeyPlaceholder"] = "フラグ名 (例: FFlagDebugDisplayFPS)",
                ["FlagValPlaceholder"] = "値 (例: True, False, 120)",
                ["BtnAddFlag"] = "追加",

                ["SysTitle"] = "システム統合 & アプリ設定",
                ["SysDesc"] = "ブラウザ連携やショートカット、言語設定を管理します",
                ["LangCardTitle"] = "表示言語 (Language)",
                ["LangCardDesc"] = "PrismStrapのUI表示言語を切り替えます",
                ["ProtocolCardTitle"] = "ブラウザ連携 (roblox-player://)",
                ["ProtocolCardDesc"] = "Webブラウザで「プレイ」をクリックした際に、PrismStrap経由でFastFlagやサウンドを適用してRobloxを起動します。",
                ["BtnProtocolRegister"] = "PrismStrapを登録する",
                ["BtnProtocolUnregister"] = "登録を解除する",
                ["ShortcutCardTitle"] = "ショートカット修復",
                ["ShortcutCardDesc"] = "デスクトップおよびスタートメニューのショートカットを再作成します",
                ["BtnRecreateShortcuts"] = "ショートカットを再作成",

                ["ToastSettingsSaved"] = "設定を保存して適用しました",
                ["ToastRobloxLaunching"] = "Robloxを起動しています...",
                ["ToastSoundApplied"] = "死亡サウンドを正常に適用しました！",
                ["ToastShortcutsRecreated"] = "ショートカットを正常に再作成しました",
                ["ToastProtocolRegistered"] = "PrismStrapをブラウザ連携に登録しました",
                ["ToastProtocolUnregistered"] = "ブラウザ連携を解除しました",
                ["ToastUpdateChecking"] = "Robloxの更新を確認中...",
                ["ToastUpdateLatest"] = "Robloxはすでに最新バージョンです",
                ["ToastUpdateFailed"] = "更新に失敗しました",
                ["ToastUpdateSuccess"] = "Robloxの更新が完了しました！",
                ["DialogNewVersionTitle"] = "PrismStrap アップデーター",
                ["DialogNewVersionFound"] = "Robloxの新しいバージョンが見つかりました。\n今すぐダウンロードして更新しますか？",
                ["DialogExeNotFound"] = "Robloxの実行ファイルが見つかりません。自動更新を試みます。",
                ["ToastFlagAdded"] = "フラグを追加しました",
                ["ToastFlagRemoved"] = "フラグを削除しました",
                ["SoundPlaying"] = "サウンドを再生中...",
                ["LoadingStartingRoblox"] = "Roblox を起動しています...",
                ["LoadingApplyingMods"] = "FastFlags とカスタムサウンドを適用中...",
                ["LoadingWaitingForRoblox"] = "Roblox の起動を待機中...",
                ["LoadingCancel"] = "キャンセル",
                ["PromptTitle"] = "PrismStrap",
                ["PromptSubtitle"] = "実行する操作を選択してください",
                ["PromptPlayRoblox"] = "Roblox をプレイ",
                ["PromptPlayRobloxDesc"] = "最適化とModを適用して起動します",
                ["PromptOpenSettings"] = "PrismStrap 設定",
                ["PromptOpenSettingsDesc"] = "FPS・グラフィック・死亡サウンドを設定",
                ["LivePlayingFormat"] = "プレイ中: {0} 人",
                ["LiveOfflineFormat"] = "オフライン: {0} 人",
                ["LiveDownloadsFormat"] = "🚀 {0} DL"
            },
            ["en"] = new()
            {
                ["NavHome"] = "Overview",
                ["NavPerf"] = "Performance",
                ["NavGfx"] = "Graphics",
                ["NavSounds"] = "Sounds",
                ["NavFlags"] = "FastFlags",
                ["NavMods"] = "Appearance & Mods",
                ["NavSys"] = "Integrations",

                ["ModsTitle"] = "Appearance & Mods",
                ["ModsDesc"] = "Customize in-game fonts, mouse cursors, and Roblox app icons",
                ["FontCardTitle"] = "In-Game Custom Font",
                ["FontCardDesc"] = "Change Roblox UI, text, and chat fonts to your favorite typeface",
                ["FontDefault"] = "Official Default (Builder Sans)",
                ["FontComicSans"] = "Comic Sans MS (Casual & Friendly)",
                ["FontSegoeUI"] = "Segoe UI (Windows 11 Fluent)",
                ["FontArial"] = "Arial (Clean & Standard)",
                ["FontCustom"] = "Custom Font (.ttf / .otf)",
                ["SelectFontFile"] = "Select Font File...",
                ["FontPreviewLabel"] = "Preview: Roblox with PrismStrap. The quick brown fox jumps over the lazy dog 1234567890",

                ["CursorCardTitle"] = "Mouse Cursor",
                ["CursorCardDesc"] = "Change the in-game Roblox cursor to classic or modern styles",
                ["CursorDefault"] = "Official Default (2020+)",
                ["CursorClassic2013"] = "Classic 2013-2020 (White Arrow Bold)",
                ["CursorClassic2006"] = "Classic 2006-2013 (Retro Pixel)",
                ["CursorCleanModern"] = "Clean Modern (Windows 11 Style)",
                ["CursorCustom"] = "Custom Cursor (.png)",
                ["SelectCursorFile"] = "Select Cursor Image...",

                ["IconCardTitle"] = "Roblox App Icon",
                ["IconCardDesc"] = "Customize the Roblox icon on your Desktop, Start Menu, and Taskbar",
                ["IconModern2022"] = "Modern 2022 (Silver)",
                ["IconTilted2017"] = "Classic 2017 (Iconic Tilted Red)",
                ["IconRedSquare2015"] = "Classic 2015 (Red Block)",
                ["IconClassic2008"] = "Classic 2008 (Legendary Red 'R')",
                ["IconPrismNeon"] = "PrismStrap Neon Prism",
                ["BtnApplyIcon"] = "Apply Icon Now",
                ["IconAppliedSuccess"] = "Roblox app icon updated successfully!",

                ["BtnLaunchRoblox"] = "Launch Roblox",
                ["BtnCheckUpdates"] = "Check Updates",
                ["StatusReady"] = "Roblox: Ready",
                ["StatusChecking"] = "Checking for updates...",
                ["StatusLatest"] = "Roblox: Latest (Ready)",
                ["StatusError"] = "Check Error",
                ["StatusDownloading"] = "Downloading update...",

                ["HomeTitle"] = "PrismStrap",
                ["HomeSubtitle"] = "Next-Generation Bootstrapper & Optimization Tool for Roblox",
                ["SysInfoTitle"] = "System Information",
                ["CurrentVersion"] = "Current Version",
                ["RobloxDir"] = "Roblox Directory",
                ["PlayerExe"] = "Executable",
                ["QuickStatsTitle"] = "Current Optimization Status",
                ["StatFps"] = "FPS Cap",
                ["StatGfx"] = "Graphics API",
                ["StatSound"] = "Death Sound",
                ["StatProtocol"] = "Browser Integration",

                ["PerfTitle"] = "Performance Settings",
                ["PerfDesc"] = "Unlock frame rate limits and optimize CPU/GPU responsiveness",
                ["FpsCardTitle"] = "Framerate Limit (FPS Unlocker)",
                ["FpsCardDesc"] = "Unlocks the default 60 FPS cap. Set to 0 for unlimited framerate.",
                ["TargetFpsLabel"] = "Target Framerate (FPS)",
                ["PresetsLabel"] = "Presets",
                ["Unlimited"] = "Unlimited",
                ["SaveSettings"] = "Save & Apply Settings",

                ["GfxTitle"] = "Graphics & Rendering",
                ["GfxDesc"] = "Configure GPU rendering backend and graphical fidelity options",
                ["ApiCardTitle"] = "Rendering API",
                ["ApiCardDesc"] = "Choose the graphics backend Roblox uses to render frames",
                ["ApiAuto"] = "Automatic (Direct3D 11 / Auto)",
                ["ApiVulkan"] = "Vulkan (Low Latency / High FPS)",
                ["ApiD3d11"] = "Direct3D 11 (High Stability)",
                ["FeaturesTitle"] = "Graphics Tweaks",
                ["MaxTexture"] = "Force Max Texture Quality",
                ["MaxTextureDesc"] = "Forces highest-resolution textures regardless of distance",
                ["DisablePostFx"] = "Disable Post-Processing",
                ["DisablePostFxDesc"] = "Disables motion blur, bloom, and color correction for clarity",
                ["ClassicMenu"] = "Classic Esc Menu",
                ["ClassicMenuDesc"] = "Restores the iconic 2020 Esc menu design",

                ["SoundsTitle"] = "Sounds & Audio",
                ["SoundsDesc"] = "Customize in-game audio effects to elevate your Roblox experience",
                ["DeathSoundCardTitle"] = "Death Sound Effect (OOF)",
                ["DeathSoundCardDesc"] = "Changes the audio effect (ouch.ogg) played when your character resets or dies.",
                ["SoundClassicOof"] = "Classic Roblox OOF Sound (2006-2022)",
                ["SoundVineBoom"] = "Vine Boom (Meme Sound)",
                ["SoundCustom"] = "Custom MP3 File",
                ["SoundDefault"] = "Roblox Default Sound (Official)",
                ["BrowseFile"] = "Browse MP3 File...",
                ["BtnPreview"] = "▶ Preview",
                ["BtnApplySound"] = "Apply Sound",
                ["CustomFileLabel"] = "Selected file: ",
                ["NoFileSelected"] = "No file selected",
                ["LblAudioEffectsTitle"] = "Audio Effect Tweaks",
                ["LblAudioEffectsDesc"] = "Customize playback volume and speed (with pitch shift)",
                ["LblVolume"] = "Volume",
                ["LblSpeed"] = "Playback Speed (Pitch shift)",
                ["BtnResetAudio"] = "Reset to Defaults",
                ["LoadingStartingRoblox"] = "Starting Roblox...",
                ["LoadingApplyingMods"] = "Applying FastFlags & custom audio...",
                ["LoadingCheckingUpdates"] = "Checking for updates...",
                ["LoadingCancel"] = "Cancel",

                ["FlagsTitle"] = "FastFlags Editor",
                ["FlagsDesc"] = "Directly manage experimental client flags (ClientAppSettings.json)",
                ["AddFlagTitle"] = "Add New FastFlag",
                ["FlagKeyPlaceholder"] = "Flag Name (e.g. FFlagDebugDisplayFPS)",
                ["FlagValPlaceholder"] = "Value (e.g. True, False, 120)",
                ["BtnAddFlag"] = "Add",

                ["SysTitle"] = "Integrations & App Settings",
                ["SysDesc"] = "Manage browser protocols, system shortcuts, and display language",
                ["LangCardTitle"] = "Display Language",
                ["LangCardDesc"] = "Switch the interface language of PrismStrap",
                ["ProtocolCardTitle"] = "Browser Protocol (roblox-player://)",
                ["ProtocolCardDesc"] = "Launches Roblox via PrismStrap with your FastFlags and sound mods when clicking 'Play' on the web.",
                ["BtnProtocolRegister"] = "Register PrismStrap",
                ["BtnProtocolUnregister"] = "Unregister",
                ["ShortcutCardTitle"] = "Repair Shortcuts",
                ["ShortcutCardDesc"] = "Recreates desktop and start menu shortcuts",
                ["BtnRecreateShortcuts"] = "Recreate Shortcuts",

                ["ToastSettingsSaved"] = "Settings saved and applied successfully",
                ["ToastRobloxLaunching"] = "Launching Roblox...",
                ["ToastSoundApplied"] = "Death sound applied successfully!",
                ["ToastShortcutsRecreated"] = "Shortcuts recreated successfully",
                ["ToastProtocolRegistered"] = "PrismStrap registered for browser launching",
                ["ToastProtocolUnregistered"] = "Browser integration unregistered",
                ["ToastUpdateChecking"] = "Checking for Roblox updates...",
                ["ToastUpdateLatest"] = "Roblox is already up to date",
                ["ToastUpdateFailed"] = "Failed to update Roblox",
                ["ToastUpdateSuccess"] = "Roblox updated successfully!",
                ["DialogNewVersionTitle"] = "PrismStrap Updater",
                ["DialogNewVersionFound"] = "A new version of Roblox was found.\nWould you like to download and install it now?",
                ["DialogExeNotFound"] = "Roblox executable not found. Checking for updates...",
                ["ToastFlagAdded"] = "Flag added successfully",
                ["ToastFlagRemoved"] = "Flag removed successfully",
                ["SoundPlaying"] = "Playing preview...",
                ["LoadingStartingRoblox"] = "Starting Roblox...",
                ["LoadingApplyingMods"] = "Applying FastFlags & custom sounds...",
                ["LoadingWaitingForRoblox"] = "Waiting for Roblox to start...",
                ["LoadingCancel"] = "Cancel",
                ["PromptTitle"] = "PrismStrap",
                ["PromptSubtitle"] = "Choose an action to proceed",
                ["PromptPlayRoblox"] = "Play Roblox",
                ["PromptPlayRobloxDesc"] = "Launch with optimizations & custom mods",
                ["PromptOpenSettings"] = "PrismStrap Settings",
                ["PromptOpenSettingsDesc"] = "Configure FPS, graphics, death sounds & flags",
                ["LivePlayingFormat"] = "Playing: {0}",
                ["LiveOfflineFormat"] = "Offline: {0}",
                ["LiveDownloadsFormat"] = "🚀 {0} DL"
            },
            ["ko"] = new()
            {
                ["NavHome"] = "개요",
                ["NavPerf"] = "성능",
                ["NavGfx"] = "그래픽",
                ["NavSounds"] = "사운드",
                ["NavFlags"] = "FastFlags",
                ["NavSys"] = "시스템 통합",

                ["BtnLaunchRoblox"] = "Roblox 실행",
                ["BtnCheckUpdates"] = "업데이트 확인",
                ["StatusReady"] = "Roblox: 준비 완료",
                ["StatusChecking"] = "업데이트 확인 중...",
                ["StatusLatest"] = "Roblox: 최신 버전 (준비 완료)",
                ["StatusError"] = "확인 오류",
                ["StatusDownloading"] = "업데이트 다운로드 중...",

                ["HomeTitle"] = "PrismStrap",
                ["HomeSubtitle"] = "Roblox를 위한 차세대 부트스트래퍼 & 최적화 도구",
                ["SysInfoTitle"] = "시스템 정보",
                ["CurrentVersion"] = "현재 버전",
                ["RobloxDir"] = "Roblox 디렉터리",
                ["PlayerExe"] = "실행 파일",
                ["QuickStatsTitle"] = "현재 최적화 상태",
                ["StatFps"] = "FPS 제한",
                ["StatGfx"] = "그래픽 API",
                ["StatSound"] = "사망 사운드",
                ["StatProtocol"] = "브라우저 연동",

                ["PerfTitle"] = "성능 설정",
                ["PerfDesc"] = "프레임 속도 제한을 해제하고 CPU/GPU 반응 속도를 최적화합니다",
                ["FpsCardTitle"] = "프레임 속도 제한 해제 (FPS Unlocker)",
                ["FpsCardDesc"] = "Roblox의 기본 60 FPS 제한을 해제합니다. 0으로 설정하면 무제한이 됩니다.",
                ["TargetFpsLabel"] = "목표 프레임 속도 (FPS)",
                ["PresetsLabel"] = "프리셋",
                ["Unlimited"] = "무제한",
                ["SaveSettings"] = "설정 저장 및 적용",

                ["GfxTitle"] = "그래픽 & 렌더링",
                ["GfxDesc"] = "GPU 렌더링 백엔드 및 그래픽 품질 옵션을 구성합니다",
                ["ApiCardTitle"] = "렌더링 API",
                ["ApiCardDesc"] = "Roblox가 화면을 렌더링할 그래픽 엔진을 선택합니다",
                ["ApiAuto"] = "자동 (기본값)",
                ["ApiVulkan"] = "Vulkan (낮은 지연 시간 / 높은 FPS)",
                ["ApiD3d11"] = "Direct3D 11 (높은 안정성)",
                ["FeaturesTitle"] = "그래픽 옵션",
                ["MaxTexture"] = "텍스처 품질 최대화 강제",
                ["MaxTextureDesc"] = "거리에 관계없이 최고 해상도의 텍스처를 강제로 적용합니다",
                ["DisablePostFx"] = "포스트 프로세싱 효과 비활성화",
                ["DisablePostFxDesc"] = "블러 및 색조 보정 등의 후처리 효과를 비활성화하여 가시성을 높입니다",
                ["ClassicMenu"] = "클래식 Esc 메뉴",
                ["ClassicMenuDesc"] = "2020년 이전의 클래식 Esc 메뉴 디자인을 복원합니다",

                ["SoundsTitle"] = "사운드 & 오디오",
                ["SoundsDesc"] = "Roblox 게임 내 효과음을 사용자 지정하여 게임 경험을 향상시킵니다",
                ["DeathSoundCardTitle"] = "사망 사운드 (OOF 소리)",
                ["DeathSoundCardDesc"] = "캐릭터가 사망하거나 리셋할 때 재생되는 효과음(ouch.ogg)을 변경합니다.",
                ["SoundClassicOof"] = "원조 Roblox OOF 사운드 (2006-2022)",
                ["SoundVineBoom"] = "Vine Boom (인기 밈 사운드)",
                ["SoundCustom"] = "커스텀 MP3 파일",
                ["SoundDefault"] = "Roblox 기본 사운드 (공식)",
                ["BrowseFile"] = "MP3 파일 선택...",
                ["BtnPreview"] = "▶ 미리듣기",
                ["BtnApplySound"] = "사운드 적용",
                ["CustomFileLabel"] = "선택된 파일: ",
                ["NoFileSelected"] = "선택된 파일 없음",
                ["LblAudioEffectsTitle"] = "오디오 효과 조정",
                ["LblAudioEffectsDesc"] = "사망 사운드의 음량 및 재생 속도(피치 연동)를 조정합니다",
                ["LblVolume"] = "음량 (Volume)",
                ["LblSpeed"] = "재생 속도 (피치 연동)",
                ["BtnResetAudio"] = "기본값으로 재설정",
                ["LoadingStartingRoblox"] = "Roblox를 시작하는 중...",
                ["LoadingApplyingMods"] = "FastFlags 및 커스텀 사운드 적용 중...",
                ["LoadingCheckingUpdates"] = "Roblox 업데이트 확인 중...",
                ["LoadingCancel"] = "취소",

                ["FlagsTitle"] = "FastFlags 편집기",
                ["FlagsDesc"] = "Roblox 내부 실험 플래그(ClientAppSettings.json)를 직접 관리합니다",
                ["AddFlagTitle"] = "새 FastFlag 추가",
                ["FlagKeyPlaceholder"] = "플래그 이름 (예: FFlagDebugDisplayFPS)",
                ["FlagValPlaceholder"] = "값 (예: True, False, 120)",
                ["BtnAddFlag"] = "추가",

                ["SysTitle"] = "시스템 통합 & 설정",
                ["SysDesc"] = "브라우저 연동, 시스템 바로가기 및 표시 언어를 관리합니다",
                ["LangCardTitle"] = "표시 언어 (Language)",
                ["LangCardDesc"] = "PrismStrap의 UI 표시 언어를 전환합니다",
                ["ProtocolCardTitle"] = "브라우저 프로토콜 연동 (roblox-player://)",
                ["ProtocolCardDesc"] = "웹사이트에서 '플레이' 클릭 시 PrismStrap을 통해 최적화 설정을 적용하여 실행합니다.",
                ["BtnProtocolRegister"] = "PrismStrap 등록",
                ["BtnProtocolUnregister"] = "연동 해제",
                ["ShortcutCardTitle"] = "바로가기 복구",
                ["ShortcutCardDesc"] = "바탕화면 및 시작 메뉴의 바로가기를 다시 생성합니다",
                ["BtnRecreateShortcuts"] = "바로가기 다시 만들기",

                ["ToastSettingsSaved"] = "설정을 저장하고 적용했습니다",
                ["ToastRobloxLaunching"] = "Roblox를 실행하고 있습니다...",
                ["ToastSoundApplied"] = "사망 사운드가 성공적으로 적용되었습니다!",
                ["ToastShortcutsRecreated"] = "바로가기가 성공적으로 다시 생성되었습니다",
                ["ToastProtocolRegistered"] = "PrismStrap이 브라우저 연동에 등록되었습니다",
                ["ToastProtocolUnregistered"] = "브라우저 연동이 해제되었습니다",
                ["ToastUpdateChecking"] = "Roblox 업데이트 확인 중...",
                ["ToastUpdateLatest"] = "Roblox가 이미 최신 버전입니다",
                ["ToastUpdateFailed"] = "Roblox 업데이트에 실패했습니다",
                ["ToastUpdateSuccess"] = "Roblox 업데이트가 완료되었습니다!",
                ["DialogNewVersionTitle"] = "PrismStrap 업데이터",
                ["DialogNewVersionFound"] = "Roblox 새 버전이 발견되었습니다.\n지금 다운로드하여 업데이트하시겠습니까?",
                ["DialogExeNotFound"] = "Roblox 실행 파일을 찾을 수 없습니다. 업데이트를 확인합니다.",
                ["ToastFlagAdded"] = "플래그가 추가되었습니다",
                ["ToastFlagRemoved"] = "플래그가 삭제되었습니다",
                ["SoundPlaying"] = "미리듣기 재생 중...",
                ["LoadingStartingRoblox"] = "Roblox를 실행하고 있습니다...",
                ["LoadingApplyingMods"] = "FastFlags 및 커스텀 사운드 적용 중...",
                ["LoadingWaitingForRoblox"] = "Roblox 실행 대기 중...",
                ["LoadingCancel"] = "취소",
                ["PromptTitle"] = "PrismStrap",
                ["PromptSubtitle"] = "실행할 작업을 선택하세요",
                ["PromptPlayRoblox"] = "Roblox 플레이",
                ["PromptPlayRobloxDesc"] = "최적화 및 모드를 적용하여 실행합니다",
                ["PromptOpenSettings"] = "PrismStrap 설정",
                ["PromptOpenSettingsDesc"] = "FPS, 그래픽, 데스 사운드 및 플래그 설정",
                ["LivePlayingFormat"] = "플레이 중: {0}명",
                ["LiveOfflineFormat"] = "오프라인: {0}명",
                ["LiveDownloadsFormat"] = "🚀 {0} DL"
            },
            ["id"] = new()
            {
                ["NavHome"] = "Ringkasan",
                ["NavPerf"] = "Performa",
                ["NavGfx"] = "Grafik",
                ["NavSounds"] = "Suara",
                ["NavFlags"] = "FastFlags",
                ["NavSys"] = "Integrasi",

                ["BtnLaunchRoblox"] = "Luncurkan Roblox",
                ["BtnCheckUpdates"] = "Periksa Pembaruan",
                ["StatusReady"] = "Roblox: Siap",
                ["StatusChecking"] = "Memeriksa pembaruan...",
                ["StatusLatest"] = "Roblox: Versi Terbaru (Siap)",
                ["StatusError"] = "Kesalahan Pemeriksaan",
                ["StatusDownloading"] = "Mengunduh pembaruan...",

                ["HomeTitle"] = "PrismStrap",
                ["HomeSubtitle"] = "Bootstrapper & Alat Optimalisasi Generasi Baru untuk Roblox",
                ["SysInfoTitle"] = "Informasi Sistem",
                ["CurrentVersion"] = "Versi Saat Ini",
                ["RobloxDir"] = "Direktori Roblox",
                ["PlayerExe"] = "File Eksekusi",
                ["QuickStatsTitle"] = "Status Optimalisasi Saat Ini",
                ["StatFps"] = "Batas FPS",
                ["StatGfx"] = "API Grafik",
                ["StatSound"] = "Suara Kematian",
                ["StatProtocol"] = "Integrasi Browser",

                ["PerfTitle"] = "Pengaturan Performa",
                ["PerfDesc"] = "Buka batas frame rate dan optimalkan responsivitas CPU/GPU",
                ["FpsCardTitle"] = "Batas Framerate (FPS Unlocker)",
                ["FpsCardDesc"] = "Membuka batas bawaan 60 FPS. Atur ke 0 untuk FPS tanpa batas.",
                ["TargetFpsLabel"] = "Target Framerate (FPS)",
                ["PresetsLabel"] = "Preset",
                ["Unlimited"] = "Tanpa Batas",
                ["SaveSettings"] = "Simpan & Terapkan Pengaturan",

                ["GfxTitle"] = "Grafik & Rendering",
                ["GfxDesc"] = "Konfigurasikan backend rendering GPU dan kualitas grafis",
                ["ApiCardTitle"] = "API Rendering",
                ["ApiCardDesc"] = "Pilih mesin grafis yang digunakan Roblox untuk rendering gambar",
                ["ApiAuto"] = "Otomatis (Default)",
                ["ApiVulkan"] = "Vulkan (Latensi Rendah / FPS Tinggi)",
                ["ApiD3d11"] = "Direct3D 11 (Stabilitas Tinggi)",
                ["FeaturesTitle"] = "Opsi Grafik",
                ["MaxTexture"] = "Paksa Kualitas Tekstur Maksimal",
                ["MaxTextureDesc"] = "Memaksa tekstur resolusi tertinggi tanpa memandang jarak",
                ["DisablePostFx"] = "Nonaktifkan Efek Pasca-Pemrosesan",
                ["DisablePostFxDesc"] = "Menonaktifkan blur dan koreksi warna untuk meningkatkan visibilitas",
                ["ClassicMenu"] = "Menu Esc Klasik",
                ["ClassicMenuDesc"] = "Mengembalikan desain menu Esc klasik tahun 2020",

                ["SoundsTitle"] = "Suara & Audio",
                ["SoundsDesc"] = "Sesuaikan efek suara dalam game untuk pengalaman bermain yang lebih baik",
                ["DeathSoundCardTitle"] = "Efek Suara Kematian (OOF)",
                ["DeathSoundCardDesc"] = "Mengubah efek suara (ouch.ogg) yang diputar saat avatar mati atau reset.",
                ["SoundClassicOof"] = "Suara Asli Roblox OOF (2006-2022)",
                ["SoundVineBoom"] = "Vine Boom (Suara Meme Populer)",
                ["SoundCustom"] = "File MP3 Kustom",
                ["SoundDefault"] = "Suara Default Roblox (Resmi)",
                ["BrowseFile"] = "Pilih File MP3...",
                ["BtnPreview"] = "▶ Putar Suara",
                ["BtnApplySound"] = "Terapkan Suara",
                ["CustomFileLabel"] = "File terpilih: ",
                ["NoFileSelected"] = "Belum ada file yang dipilih",
                ["LblAudioEffectsTitle"] = "Pengaturan Efek Audio",
                ["LblAudioEffectsDesc"] = "Sesuaikan volume dan kecepatan pemutaran (dengan perubahan nada)",
                ["LblVolume"] = "Volume",
                ["LblSpeed"] = "Kecepatan Pemutaran (Nada)",
                ["BtnResetAudio"] = "Reset ke Default",
                ["LoadingStartingRoblox"] = "Memulai Roblox...",
                ["LoadingApplyingMods"] = "Menerapkan FastFlags & audio kustom...",
                ["LoadingCheckingUpdates"] = "Memeriksa pembaruan Roblox...",
                ["LoadingCancel"] = "Batal",

                ["FlagsTitle"] = "Editor FastFlags",
                ["FlagsDesc"] = "Kelola flag eksperimental Roblox (ClientAppSettings.json) secara langsung",
                ["AddFlagTitle"] = "Tambah FastFlag Baru",
                ["FlagKeyPlaceholder"] = "Nama Flag (contoh: FFlagDebugDisplayFPS)",
                ["FlagValPlaceholder"] = "Nilai (contoh: True, False, 120)",
                ["BtnAddFlag"] = "Tambah",

                ["SysTitle"] = "Integrasi Sistem & Pengaturan",
                ["SysDesc"] = "Kelola protokol browser, pintasan sistem, dan bahasa tampilan",
                ["LangCardTitle"] = "Bahasa Tampilan (Language)",
                ["LangCardDesc"] = "Ganti bahasa antarmuka PrismStrap",
                ["ProtocolCardTitle"] = "Protokol Browser (roblox-player://)",
                ["ProtocolCardDesc"] = "Meluncurkan Roblox melalui PrismStrap dengan konfigurasi optimal saat mengklik 'Play' di web.",
                ["BtnProtocolRegister"] = "Daftarkan PrismStrap",
                ["BtnProtocolUnregister"] = "Batalkan Pendaftaran",
                ["ShortcutCardTitle"] = "Perbaiki Pintasan",
                ["ShortcutCardDesc"] = "Membuat ulang pintasan desktop dan menu mulai",
                ["BtnRecreateShortcuts"] = "Buat Ulang Pintasan",

                ["ToastSettingsSaved"] = "Pengaturan berhasil disimpan dan diterapkan",
                ["ToastRobloxLaunching"] = "Meluncurkan Roblox...",
                ["ToastSoundApplied"] = "Suara kematian berhasil diterapkan!",
                ["ToastShortcutsRecreated"] = "Pintasan berhasil dibuat ulang",
                ["ToastProtocolRegistered"] = "PrismStrap terdaftar untuk peluncuran browser",
                ["ToastProtocolUnregistered"] = "Integrasi browser dibatalkan",
                ["ToastUpdateChecking"] = "Memeriksa pembaruan Roblox...",
                ["ToastUpdateLatest"] = "Roblox sudah versi terbaru",
                ["ToastUpdateFailed"] = "Gagal memperbarui Roblox",
                ["ToastUpdateSuccess"] = "Roblox berhasil diperbarui!",
                ["DialogNewVersionTitle"] = "Pembaruan PrismStrap",
                ["DialogNewVersionFound"] = "Versi baru Roblox ditemukan.\nApakah Anda ingin mengunduh dan memperbaruinya sekarang?",
                ["DialogExeNotFound"] = "File eksekusi Roblox tidak ditemukan. Memeriksa pembaruan...",
                ["ToastFlagAdded"] = "Flag berhasil ditambahkan",
                ["ToastFlagRemoved"] = "Flag berhasil dihapus",
                ["SoundPlaying"] = "Memutar suara...",
                ["LoadingStartingRoblox"] = "Memulai Roblox...",
                ["LoadingApplyingMods"] = "Menerapkan FastFlags & efek suara...",
                ["LoadingWaitingForRoblox"] = "Menunggu Roblox dimulai...",
                ["LoadingCancel"] = "Batal",
                ["PromptTitle"] = "PrismStrap",
                ["PromptSubtitle"] = "Pilih tindakan untuk melanjutkan",
                ["PromptPlayRoblox"] = "Mainkan Roblox",
                ["PromptPlayRobloxDesc"] = "Luncurkan dengan optimasi & mod kustom",
                ["PromptOpenSettings"] = "Pengaturan PrismStrap",
                ["PromptOpenSettingsDesc"] = "Atur FPS, grafik, suara kematian & flags",
                ["LivePlayingFormat"] = "Bermain: {0}",
                ["LiveOfflineFormat"] = "Offline: {0}",
                ["LiveDownloadsFormat"] = "🚀 {0} DL"
            },
            ["zh"] = new()
            {
                ["NavHome"] = "概览",
                ["NavPerf"] = "性能",
                ["NavGfx"] = "图形",
                ["NavSounds"] = "声音",
                ["NavFlags"] = "FastFlags",
                ["NavSys"] = "系统集成",

                ["BtnLaunchRoblox"] = "启动 Roblox",
                ["BtnCheckUpdates"] = "检查更新",
                ["StatusReady"] = "Roblox: 就绪",
                ["StatusChecking"] = "正在检查更新...",
                ["StatusLatest"] = "Roblox: 最新版本 (就绪)",
                ["StatusError"] = "检查错误",
                ["StatusDownloading"] = "正在下载更新...",

                ["HomeTitle"] = "PrismStrap",
                ["HomeSubtitle"] = "专为 Roblox 打造的次世代启动引导器与优化工具",
                ["SysInfoTitle"] = "系统信息",
                ["CurrentVersion"] = "当前版本",
                ["RobloxDir"] = "Roblox 目录",
                ["PlayerExe"] = "执行文件",
                ["QuickStatsTitle"] = "当前优化状态",
                ["StatFps"] = "FPS 限制",
                ["StatGfx"] = "图形 API",
                ["StatSound"] = "死亡音效",
                ["StatProtocol"] = "浏览器关联",

                ["PerfTitle"] = "性能设置",
                ["PerfDesc"] = "解锁帧率限制并优化 CPU/GPU 响应性能",
                ["FpsCardTitle"] = "解锁帧率限制 (FPS Unlocker)",
                ["FpsCardDesc"] = "解除 Roblox 默认的 60 FPS 限制。设置为 0 则为无限制帧率。",
                ["TargetFpsLabel"] = "目标帧率 (FPS)",
                ["PresetsLabel"] = "预设选项",
                ["Unlimited"] = "无限制",
                ["SaveSettings"] = "保存并应用设置",

                ["GfxTitle"] = "图形与渲染",
                ["GfxDesc"] = "配置 GPU 渲染后端与图形画质选项",
                ["ApiCardTitle"] = "渲染 API",
                ["ApiCardDesc"] = "选择 Roblox 用于绘制画面的图形引擎",
                ["ApiAuto"] = "自动 (默认 / Direct3D 11)",
                ["ApiVulkan"] = "Vulkan (低延迟 / 高帧率)",
                ["ApiD3d11"] = "Direct3D 11 (高稳定性)",
                ["FeaturesTitle"] = "图形画质增强",
                ["MaxTexture"] = "强制最高纹理质量",
                ["MaxTextureDesc"] = "无论距离远近均强制加载最高分辨率贴图",
                ["DisablePostFx"] = "禁用后处理特效",
                ["DisablePostFxDesc"] = "关闭动态模糊、泛光和色彩校正以提高画面清晰度",
                ["ClassicMenu"] = "经典 Esc 菜单",
                ["ClassicMenuDesc"] = "恢复 2020 年以前的经典 Esc 菜单样式",

                ["SoundsTitle"] = "声音与音效",
                ["SoundsDesc"] = "自定义游戏内音效，打造专属 Roblox 体验",
                ["DeathSoundCardTitle"] = "死亡音效 (OOF 声)",
                ["DeathSoundCardDesc"] = "更改角色死亡或重置时播放的声音效果 (ouch.ogg)。",
                ["SoundClassicOof"] = "原版 Roblox OOF 音效 (2006-2022)",
                ["SoundVineBoom"] = "Vine Boom (网络热门梗音效)",
                ["SoundCustom"] = "自定义 MP3 音频",
                ["SoundDefault"] = "Roblox 默认音效 (官方标准)",
                ["BrowseFile"] = "选择 MP3 文件...",
                ["BtnPreview"] = "▶ 试听",
                ["BtnApplySound"] = "应用音效",
                ["CustomFileLabel"] = "已选文件: ",
                ["NoFileSelected"] = "尚未选择文件",
                ["LblAudioEffectsTitle"] = "音频效果调节",
                ["LblAudioEffectsDesc"] = "自定义死亡音效的播放音量与速度 (音调联动)",
                ["LblVolume"] = "音量 (Volume)",
                ["LblSpeed"] = "播放速度 (音调联动)",
                ["BtnResetAudio"] = "重置为默认值",
                ["LoadingStartingRoblox"] = "正在启动 Roblox...",
                ["LoadingApplyingMods"] = "正在应用 FastFlags 与自定义音效...",
                ["LoadingCheckingUpdates"] = "正在检查 Roblox 更新...",
                ["LoadingCancel"] = "取消",

                ["FlagsTitle"] = "FastFlags 编辑器",
                ["FlagsDesc"] = "直接管理 Roblox 内部实验性功能开关 (ClientAppSettings.json)",
                ["AddFlagTitle"] = "添加新的 FastFlag",
                ["FlagKeyPlaceholder"] = "Flag 名称 (例如: FFlagDebugDisplayFPS)",
                ["FlagValPlaceholder"] = "值 (例如: True, False, 120)",
                ["BtnAddFlag"] = "添加",

                ["SysTitle"] = "系统集成与设置",
                ["SysDesc"] = "管理浏览器协议关联、系统快捷方式及界面显示语言",
                ["LangCardTitle"] = "显示语言 (Language)",
                ["LangCardDesc"] = "切换 PrismStrap 的界面显示语言",
                ["ProtocolCardTitle"] = "浏览器关联协议 (roblox-player://)",
                ["ProtocolCardDesc"] = "在网页上点击“开始游戏”时，自动通过 PrismStrap 附带优化参数启动 Roblox。",
                ["BtnProtocolRegister"] = "注册关联",
                ["BtnProtocolUnregister"] = "解除关联",
                ["ShortcutCardTitle"] = "快捷方式修复",
                ["ShortcutCardDesc"] = "重新生成桌面和开始菜单的快捷方式",
                ["BtnRecreateShortcuts"] = "重新创建快捷方式",

                ["ToastSettingsSaved"] = "设置已成功保存并应用",
                ["ToastRobloxLaunching"] = "正在启动 Roblox...",
                ["ToastSoundApplied"] = "死亡音效已成功应用！",
                ["ToastShortcutsRecreated"] = "快捷方式已重新创建",
                ["ToastProtocolRegistered"] = "已成功关联浏览器启动协议",
                ["ToastProtocolUnregistered"] = "已解除浏览器协议关联",
                ["ToastUpdateChecking"] = "正在检查 Roblox 更新...",
                ["ToastUpdateLatest"] = "Roblox 已经是最新版本",
                ["ToastUpdateFailed"] = "更新 Roblox 失败",
                ["ToastUpdateSuccess"] = "Roblox 更新完成！",
                ["DialogNewVersionTitle"] = "PrismStrap 更新器",
                ["DialogNewVersionFound"] = "发现 Roblox 的新版本。\n是否立即下载并更新？",
                ["DialogExeNotFound"] = "未找到 Roblox 可执行文件，正在尝试更新...",
                ["ToastFlagAdded"] = "Flag 添加成功",
                ["ToastFlagRemoved"] = "Flag 删除成功",
                ["SoundPlaying"] = "正在试听音效...",
                ["LoadingStartingRoblox"] = "正在启动 Roblox...",
                ["LoadingApplyingMods"] = "正在应用 FastFlags 和自定义音效...",
                ["LoadingWaitingForRoblox"] = "等待 Roblox 启动...",
                ["LoadingCancel"] = "取消",
                ["PromptTitle"] = "PrismStrap",
                ["PromptSubtitle"] = "选择要执行的操作",
                ["PromptPlayRoblox"] = "启动 Roblox",
                ["PromptPlayRobloxDesc"] = "应用优化和自定义Mod并启动",
                ["PromptOpenSettings"] = "PrismStrap 设置",
                ["PromptOpenSettingsDesc"] = "配置 FPS、图形、死亡音效和 FastFlags",
                ["LivePlayingFormat"] = "正在游戏: {0}人",
                ["LiveOfflineFormat"] = "离线: {0}人",
                ["LiveDownloadsFormat"] = "🚀 {0} 下载"
            },
            ["pt"] = new()
            {
                ["NavHome"] = "Visão Geral",
                ["NavPerf"] = "Desempenho",
                ["NavGfx"] = "Gráficos",
                ["NavSounds"] = "Sons",
                ["NavFlags"] = "FastFlags",
                ["NavSys"] = "Integrações",

                ["BtnLaunchRoblox"] = "Iniciar Roblox",
                ["BtnCheckUpdates"] = "Verificar Atualizações",
                ["StatusReady"] = "Roblox: Pronto",
                ["StatusChecking"] = "Verificando atualizações...",
                ["StatusLatest"] = "Roblox: Atualizado (Pronto)",
                ["StatusError"] = "Erro de Verificação",
                ["StatusDownloading"] = "Baixando atualização...",

                ["HomeTitle"] = "PrismStrap",
                ["HomeSubtitle"] = "Bootstrapper e Otimizador de Nova Geração para o Roblox",
                ["SysInfoTitle"] = "Informações do Sistema",
                ["CurrentVersion"] = "Versão Atual",
                ["RobloxDir"] = "Diretório do Roblox",
                ["PlayerExe"] = "Executável",
                ["QuickStatsTitle"] = "Status de Otimização Atual",
                ["StatFps"] = "Limite de FPS",
                ["StatGfx"] = "API Gráfica",
                ["StatSound"] = "Som de Morte",
                ["StatProtocol"] = "Integração do Navegador",

                ["PerfTitle"] = "Configurações de Desempenho",
                ["PerfDesc"] = "Desbloqueie taxas de quadros e otimize a resposta de CPU e GPU",
                ["FpsCardTitle"] = "Desbloqueador de FPS (FPS Unlocker)",
                ["FpsCardDesc"] = "Remove o limite padrão de 60 FPS. Defina como 0 para FPS ilimitado.",
                ["TargetFpsLabel"] = "Taxa de Quadros Alvo (FPS)",
                ["PresetsLabel"] = "Predefinições",
                ["Unlimited"] = "Ilimitado",
                ["SaveSettings"] = "Salvar e Aplicar Configurações",

                ["GfxTitle"] = "Gráficos e Renderização",
                ["GfxDesc"] = "Configure a API de renderização e opções de fidelidade visual",
                ["ApiCardTitle"] = "API de Renderização",
                ["ApiCardDesc"] = "Escolha o mecanismo gráfico que o Roblox usa para desenhar quadros",
                ["ApiAuto"] = "Automático (Padrão / Direct3D 11)",
                ["ApiVulkan"] = "Vulkan (Baixa Latência / Alto FPS)",
                ["ApiD3d11"] = "Direct3D 11 (Alta Estabilidade)",
                ["FeaturesTitle"] = "Opções Gráficas",
                ["MaxTexture"] = "Forçar Qualidade Máxima de Textura",
                ["MaxTextureDesc"] = "Força texturas na resolução mais alta independentemente da distância",
                ["DisablePostFx"] = "Desativar Pós-Processamento",
                ["DisablePostFxDesc"] = "Desativa desfoque e correção de cores para maior clareza visual",
                ["ClassicMenu"] = "Menu Esc Clássico",
                ["ClassicMenuDesc"] = "Restaura o design icônico do menu Esc de 2020",

                ["SoundsTitle"] = "Sons e Áudio",
                ["SoundsDesc"] = "Personalize os efeitos sonoros do jogo para melhorar sua experiência",
                ["DeathSoundCardTitle"] = "Efeito Sonoro de Morte (OOF)",
                ["DeathSoundCardDesc"] = "Altera o efeito sonoro (ouch.ogg) tocado quando o seu avatar morre ou reseta.",
                ["SoundClassicOof"] = "Som Clássico OOF do Roblox (2006-2022)",
                ["SoundVineBoom"] = "Vine Boom (Meme Popular)",
                ["SoundCustom"] = "Arquivo MP3 Personalizado",
                ["SoundDefault"] = "Som Padrão do Roblox (Oficial)",
                ["BrowseFile"] = "Selecionar Arquivo MP3...",
                ["BtnPreview"] = "▶ Ouvir Prévia",
                ["BtnApplySound"] = "Aplicar Som",
                ["CustomFileLabel"] = "Arquivo selecionado: ",
                ["NoFileSelected"] = "Nenhum arquivo selecionado",
                ["LblAudioEffectsTitle"] = "Ajustes de Efeitos Sonoros",
                ["LblAudioEffectsDesc"] = "Personalize o volume e a velocidade de reprodução (com alteração de tom)",
                ["LblVolume"] = "Volume",
                ["LblSpeed"] = "Velocidade de Reprodução (Tom)",
                ["BtnResetAudio"] = "Restaurar Padrões",
                ["LoadingStartingRoblox"] = "Iniciando o Roblox...",
                ["LoadingApplyingMods"] = "Aplicando FastFlags e áudio personalizado...",
                ["LoadingCheckingUpdates"] = "Verificando atualizações do Roblox...",
                ["LoadingCancel"] = "Cancelar",

                ["FlagsTitle"] = "Editor de FastFlags",
                ["FlagsDesc"] = "Gerencie diretamente flags experimentais do Roblox (ClientAppSettings.json)",
                ["AddFlagTitle"] = "Adicionar Nova FastFlag",
                ["FlagKeyPlaceholder"] = "Nome da Flag (ex: FFlagDebugDisplayFPS)",
                ["FlagValPlaceholder"] = "Valor (ex: True, False, 120)",
                ["BtnAddFlag"] = "Adicionar",

                ["SysTitle"] = "Integrações e Configurações do Sistema",
                ["SysDesc"] = "Gerencie protocolos do navegador, atalhos do sistema e idioma",
                ["LangCardTitle"] = "Idioma de Exibição (Language)",
                ["LangCardDesc"] = "Alterne o idioma da interface do PrismStrap",
                ["ProtocolCardTitle"] = "Protocolo do Navegador (roblox-player://)",
                ["ProtocolCardDesc"] = "Inicia o Roblox pelo PrismStrap aplicando otimizações ao clicar em 'Jogar' na web.",
                ["BtnProtocolRegister"] = "Registrar PrismStrap",
                ["BtnProtocolUnregister"] = "Desregistrar",
                ["ShortcutCardTitle"] = "Reparar Atalhos",
                ["ShortcutCardDesc"] = "Recria os atalhos da área de trabalho e do menu iniciar",
                ["BtnRecreateShortcuts"] = "Recriar Atalhos",

                ["ToastSettingsSaved"] = "Configurações salvas e aplicadas com sucesso",
                ["ToastRobloxLaunching"] = "Iniciando o Roblox...",
                ["ToastSoundApplied"] = "Som de morte aplicado com sucesso!",
                ["ToastShortcutsRecreated"] = "Atalhos recriados com sucesso",
                ["ToastProtocolRegistered"] = "PrismStrap registrado para inicialização pelo navegador",
                ["ToastProtocolUnregistered"] = "Integração do navegador desregistrada",
                ["ToastUpdateChecking"] = "Verificando atualizações do Roblox...",
                ["ToastUpdateLatest"] = "O Roblox já está na versão mais recente",
                ["ToastUpdateFailed"] = "Falha ao atualizar o Roblox",
                ["ToastUpdateSuccess"] = "Roblox atualizado com sucesso!",
                ["DialogNewVersionTitle"] = "Atualizador do PrismStrap",
                ["DialogNewVersionFound"] = "Uma nova versão do Roblox foi encontrada.\nDeseja baixar e instalar agora?",
                ["DialogExeNotFound"] = "Executável do Roblox não encontrado. Verificando atualizações...",
                ["ToastFlagAdded"] = "Flag adicionada com sucesso",
                ["ToastFlagRemoved"] = "Flag removida com sucesso",
                ["SoundPlaying"] = "Reproduzindo prévia...",
                ["LoadingStartingRoblox"] = "Iniciando o Roblox...",
                ["LoadingApplyingMods"] = "Aplicando FastFlags e sons personalizados...",
                ["LoadingWaitingForRoblox"] = "Aguardando o Roblox iniciar...",
                ["LoadingCancel"] = "Cancelar",
                ["PromptTitle"] = "PrismStrap",
                ["PromptSubtitle"] = "Escolha uma ação para continuar",
                ["PromptPlayRoblox"] = "Jogar Roblox",
                ["PromptPlayRobloxDesc"] = "Iniciar com otimizações e mods personalizados",
                ["PromptOpenSettings"] = "Configurações do PrismStrap",
                ["PromptOpenSettingsDesc"] = "Configurar FPS, gráficos, sons de morte e flags",
                ["LivePlayingFormat"] = "Jogando: {0}",
                ["LiveOfflineFormat"] = "Offline: {0}",
                ["LiveDownloadsFormat"] = "🚀 {0} DL"
            }
        };

        public static event Action? LanguageChanged;

        public static void SetLanguage(string langCode)
        {
            if (Translations.ContainsKey(langCode))
            {
                CurrentLanguage = langCode;
                LanguageChanged?.Invoke();
            }
        }

        public static string Get(string key)
        {
            if (Translations.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            {
                return val;
            }
            if (Translations["en"].TryGetValue(key, out var fallback))
            {
                return fallback;
            }
            return key;
        }
    }
}
